---
language: python
dist: xenial
python:
  - "2.7"
  - "3.6"
services:
  - docker
install:
  - pip install ansible==2.7.10 molecule docker
script:
  - molecule --version
  - ansible --version
  - molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
